### ISSUE TITLE
Add queue

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/hotseat-api#2]
### Description

Add a queue in order to process emails 

### Tasks 

- [x] Add a provider for the Queue, since it can be implemented with many libraries (The best options, for now, is probably [Bull](https://github.com/OptimalBits/bull))
- [x] Add a folder to store all the jobs, inside the dependencies container folder. The job needs to be registered as a dependency because we'll need to create fakes for testing purposes. 
- [x] Create a file to initialize the queue on another process 

### Notes 

Pay attention on the order that the dependencies are being registered 

1. Providers (Template, Mail, Queue, etc)
2. Jobs (MailProviderJob, etc)

```
import './providers';
import './jobs';
```
